// Routes that should NOT trigger a redirect even if the user is not authenticated
export const WHITELIST_ROUTES = [
  "/turneringer",
  "/turneringer/check-in",
  "/turneringer/info",
  "/turneringer/info/briefing",
  "/turneringer/info/generelt",
  "/turneringer/regler",
  "/turneringer/baneoversigt",
  "/player/:playerId/:rowId, /court-times",
  "/register",
  "/turneringer",
  "/turneringer/info",
  "/turneringer/info/briefing",
  "/turneringer/info/generelt",
  "/",
  "/player/:playerId/:rowId",
  "/player/:playerId",
  "/InstallPrompt",
  "/glemt-adgangskode",
  "/reset-password/:token",
  "/install",
  "/lunarGlobal",
];
